/**
 * Site Configuration
 *
 * This file contains all site-specific settings that can be customized
 * for different niches (Fashion, Fitness, Food, Tech, etc.)
 *
 * GENERATED FILE - Do not edit manually
 * Generated by: Site Generator
 * Generated at: 2025-11-07T15:25:52.404Z
 */

import { getLanguageConfig, type SupportedLanguage } from './languages';

export interface SiteConfig {
  // Basic Site Information
  site: {
    name: string;
    tagline: string;
    description: string;
    url: string;
    wordpressUrl: string;
    language: string;
    locale: string;
  };

  // Brand Identity
  brand: {
    colors: {
      primary: string;
      secondary: string;
      accent: string;
      background: string;
      text: string;
      textSecondary?: string;
    };
    typography: {
      headingFont: string;
      bodyFont: string;
    };
    logo?: {
      text: string;
      subtitle?: string;
    };
  };

  // Content Settings
  content: {
    postsPerPage: number;
    relatedPostsCount: number;
    excerptLength: number;
    featuredImageRatio: string;
    showAuthor: boolean;
    showDate: boolean;
    showCategories: boolean;
    showTags: boolean;
  };

  // Navigation
  navigation: {
    header: Array<{
      label: string;
      href: string;
      external?: boolean;
    }>;
    footer: {
      sections: Array<{
        title: string;
        links: Array<{
          label: string;
          href: string;
          external?: boolean;
        }>;
      }>;
    };
    menuCategories?: Array<{
      name: string;
      slug: string;
    }>;
  };

  // Social Media
  social: {
    pinterest?: string;
    instagram?: string;
    facebook?: string;
    twitter?: string;
    youtube?: string;
    tiktok?: string;
    email?: string;
  };

  // Analytics & Tracking
  analytics: {
    googleAnalytics?: string;
    googleAdsense?: string;
    facebookPixel?: string;
    pinterestTag?: string;
  };

  // Legal Information
  legal: {
    companyName: string;
    contactEmail: string;
    country: string;
    jurisdiction: string;
  };

  // Hero Section (Homepage)
  hero: {
    title: string;
    subtitle: string;
    backgroundImage: string;
    cta?: {
      text: string;
      href: string;
    };
  };

  // Persona / About Page
  persona?: {
    name: string;
    role: string;
    bio: string;
    story: string;
    expertise: string[];
    image?: string;
    quote?: string;
    achievements?: string[];
  };

  // Features / Highlights
  features?: Array<{
    title: string;
    description: string;
    icon?: string;
  }>;

  // Custom Scripts/Code Injection
  customScripts?: {
    headScripts?: string;
    bodyStartScripts?: string;
    bodyEndScripts?: string;
  };

  // SEO Defaults
  seo: {
    titleTemplate: string;
    defaultTitle: string;
    defaultDescription: string;
    twitterHandle?: string;
  };
}

/**
 * Current Site Configuration
 */
export const siteConfig: SiteConfig = {
  site: {
    name: "Peach & Chic ",
    tagline: "Elegance Made Simple",
    description: "Discover the latest fashion trends and beauty tips at Peach & Chic. Your daily destination for style inspiration, makeup tutorials, and expert fashion advice.",
    url: process.env.NEXT_PUBLIC_SITE_URL || "https://peachandchic.com",
    wordpressUrl: process.env.NEXT_PUBLIC_WORDPRESS_API_URL?.replace('/graphql', '') || "https://wp.peachandchic.com",
    language: "en",
    locale: "en_US",
  },

  brand: {
    colors: {
      "primary": "#FFBCB5",
      "secondary": "#F8E1E0",
      "accent": "d68b88",
      "background": "#FFF5F5",
      "text": "#4A3B3B",
      "textSecondary": "#ffffff"
},
    typography: {
      "headingFont": "Playfair Display",
      "bodyFont": "Lato"
},
    logo: {
      text: "PEACH & CHIC ",
      subtitle: "Elegance Made Simple",
    },
  },

  content: {
    postsPerPage: 12,
    relatedPostsCount: 5,
    excerptLength: 160,
    featuredImageRatio: "3:2",
    showAuthor: true,
    showDate: true,
    showCategories: true,
    showTags: true,
  },

  navigation: {
    header: [
      {
            "label": "Home",
            "href": "/"
      },
      {
            "label": "About",
            "href": "/about"
      }
],
    footer: {
      sections: [
        {
                "title": "Explore",
                "links": [
                        {
                                "label": "Beauty",
                                "href": "/category/beauty"
                        },
                        {
                                "label": "Fashion",
                                "href": "/category/fashion"
                        },
                        {
                                "label": "Magazine",
                                "href": "/category/magazine"
                        }
                ]
        },
        {
                "title": "Legal",
                "links": [
                        {
                                "label": "Privacy Policy",
                                "href": "/privacy"
                        },
                        {
                                "label": "Terms of Service",
                                "href": "/terms"
                        },
                        {
                                "label": "Disclaimer",
                                "href": "/disclaimer"
                        }
                ]
        },
        {
                "title": "Follow",
                "links": [
                        {
                                "label": "Pinterest",
                                "href": "https://pinterest.com/",
                                "external": true
                        }
                ]
        }
],
    },
    menuCategories: [
      {
            "name": "Beauty",
            "slug": "beauty"
      },
      {
            "name": "Fashion",
            "slug": "fashion"
      },
      {
            "name": "Magazine",
            "slug": "magazine"
      }
],
  },

  social: {
    pinterest: "https://pinterest.com/",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    tiktok: "",
    email: "",
  },

  analytics: {
    // googleAnalytics: "",
    // googleAdsense: "",
  },

  customScripts: {
    headScripts: `<script defer data-domain="peachandchic.com" src="https://stats.tripleadigital.de/js/script.js"></script>`,
    // bodyStartScripts: "",
    // bodyEndScripts: "",
  },

  legal: {
    companyName: "Triple A Digital",
    contactEmail: "",
    country: "Germany",
    jurisdiction: "Germany",
  },

  hero: {
    "title": "Discover Your Style",
    "subtitle": "Fashion, Beauty & Lifestyle Inspiration",
    "backgroundImage": "/images/hero-bg.jpg",
    "cta": {
        "text": "Explore Now",
        "href": "#categories"
    }
},

  persona: {
    "name": "Sophia Rosenberg",
    "role": "Fashion & Beauty Consultant for Timeless Elegance",
    "bio": "After 30 years in the fashion industry, I discovered my true calling: helping women over 50 embrace their most radiant, confident selves. Style has no expiration date—it only gets better with time.",
    "story": "My journey into the world of fashion began in my twenties, working behind the scenes at fashion weeks across Europe. I spent decades styling models, celebrities, and executives, always chasing the next trend. But at 52, something shifted. I looked around and realized the fashion industry was ignoring the most elegant, sophisticated women—those who had lived, learned, and developed their own sense of style.\n\nThat's when I founded Peach & Chic. After watching my own mother struggle to find fashion advice that spoke to her, I knew there was a gap that needed filling. Women over 50 don't want to dress like their daughters, nor do they want to fade into the background. They want to celebrate who they've become—confident, discerning, and unapologetically themselves.\n\nNow, at 58, I've never felt more beautiful or more certain of my purpose. I combine my decades of industry expertise with a deep understanding of how our bodies, skin, and style preferences evolve. Every recommendation I make comes from personal experience and extensive research. I test products on my own mature skin, I wear the clothes I recommend, and I understand the balance between timeless elegance and contemporary sophistication.\n\nPeach & Chic isn't just a blog—it's a celebration of the woman you've become and the exciting style journey that lies ahead. Because true beauty and style? They're ageless.",
    "expertise": [
        "Mature Skin Skincare",
        "Age-Appropriate Fashion Styling",
        "Luxury Beauty Products",
        "Wardrobe Consulting",
        "Color Analysis for Mature Women",
        "Anti-Aging Treatments"
    ],
    "quote": "Elegance is not about being noticed, it's about being remembered—and we deserve to be unforgettable.",
    "achievements": [
        "Former Senior Stylist at Paris Fashion Week",
        "Certified Color Analysis Specialist",
        "Featured in Vogue Germany's 'Ageless Beauty' Issue",
        "Author of 'Style After 50: A Modern Guide'"
    ]
},
  seo: {
    titleTemplate: "%s | Peach & Chic ",
    defaultTitle: "Peach & Chic  - Elegance Made Simple",
    defaultDescription: "Discover the latest fashion trends and beauty tips at Peach & Chic. Your daily destination for style inspiration, makeup tutorials, and expert fashion advice.",
  },
};

/**
 * Helper function to get nested config values safely
 */
export function getConfigValue<T>(path: string, defaultValue?: T): T | undefined {
  const keys = path.split('.');
  let value: any = siteConfig;

  for (const key of keys) {
    if (value && typeof value === 'object' && key in value) {
      value = value[key];
    } else {
      return defaultValue;
    }
  }

  return value as T;
}

/**
 * Get language configuration for current site
 */
export function getLanguage() {
  const langCode = siteConfig.site.language as SupportedLanguage;
  return getLanguageConfig(langCode);
}

/**
 * Get translated UI strings
 */
export function t() {
  return getLanguage().ui;
}
